### ISSUE TITLE
Define-XML change and the dreaded /~and~/

### ISSUE THREAD

**Issue by cpshadle** [cdisc-org/cosa#25]
Lex reached out with some errors in: https://cosa.cdisc.org/directory/defineStylesheets
 
1.  First is that when you click on that link it continually builds a URL by repeatedly appending /~and~/

2.  He'd like an update to the text.

From:

> Solution
> To provide a Define-XML v2.1 XSL stylesheet that can be used in the case of electronic submissions to regulatory agencies.
> The stylesheets for version 2.0 are located in this [Define-XML v2.1 Stylesheet](https://github.com/lexjansen/define-xml-2.1-stylesheets) repository whereas the stylesheets for 2.1 are located in [Define-XML v2.0 Stylesheet](https://github.com/lexjansen/define-xml-2.0-stylesheets).
 
To:
 

> Solution
> To provide Define-XML v2.x XSL stylesheets that can be used in the case of electronic submissions to regulatory agencies.
> The stylesheets for version 2.1 are located in this [Define-XML v2.1 Stylesheet](https://github.com/lexjansen/define-xml-2.1-stylesheets) repository whereas the stylesheets for 2.0 are located in [Define-XML v2.0 Stylesheet](https://github.com/lexjansen/define-xml-2.0-stylesheets).

**Comment by KatjaGlassConsulting** [comment]
solved
