### ISSUE TITLE
Logo when pasting into Social Media

### ISSUE THREAD

**Issue by cpshadle** [cdisc-org/cosa#26]
When opening the COSA site in my browsers, I see the logo on the tab.

However, when pasting the link into LinkedIn, it rendered a title area but no logo.

This is not functionally important but would be nice if this can be added.
![image](https://user-images.githubusercontent.com/86124727/157718432-ece89921-526b-4cc6-ad12-b9a4af4bcc0e.png)

**Comment by KatjaGlassConsulting** [comment]
include an image meta tag which is used by linkedIn (use a screenshot)
